### ISSUE TITLE
[1.18.1] Grave not being placed if death is under Y0, "There was nowhere to place the grave!" even with sufficient space

### ISSUE THREAD

**Issue by Not-February** [Lothrazar/SimpleTomb#10]
Minecraft Version: 1.18.1

Forge Version: 39.0.44

Mod Version: 1.0.10

Single Player or Server: Single Player

Describe problem (what you were doing; what happened; what should have happened):

I tested this standalone at two different Y levels, each below Y0 but above Y-64(the new lower bound of world height), and graves propagate just fine when I'm above that range, but below that range the grave never thinks it has enough space. Dying in a cave or above ground above Y0 works fine and the grave is generated as expected.

Each of the places I died were on solid ground with at least a 3x3 space around me.

I kind of wonder if this is related to #4? Cave air became an actual generating thing in 1.18 AFAIK

Log file link: https://gist.github.com/Febilian/cc376abd6e77cbf18224e1c9cf30f107

Video/images/gifs (direct upload or link): 

![image](https://user-images.githubusercontent.com/13922447/149991137-2b2b9258-7662-498c-a387-d9361922189c.png)

**Comment by MPThLee** [comment]
I was implementing the fix on #9 but somehow grave on nether doesn’t working(had no time to spend what causes it.) so i just leaving to another grave mod.

**Comment by Mrbysco** [comment]
1.0.12 should fix this
